@startuml logout
' TODO: check speciality does exist
hide footbox
title "اقزودن نوع خدمت متخصص"
actor       "متخصص" as user
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":SpecialistController" as SpecialistController
participant ":SpecialityCatalogue" as SpecialityCatalogue
participant ":Speciality" as Speciality
participant ":SpecialityCertificateDTO" as SpecialityCertificateDTO
participant ":SpecialistCatalogue" as SpecialistCatalogue
participant ":Specialist" as Specialist
participant ":SpecialityCertificateController" as SpecialityCertificateController
participant ":SpecialityCertificate" as SpecialityCertificate
participant ":SpecialityCertificateCatalogue" as SpecialityCertificateCatalogue
database Database

note left of user
    متخصص باید در سامانه
    وارد شده باشد
end note

user -> ReactApp: 
ReactApp -> RestAPI : http_request
RestAPI -> SpecialistController : addCertificate(id, certificate)
SpecialistController -> SpecialityCatalogue : findById(id)
SpecialityCatalogue -> Database : sql_query
return tuple
alt#gold #pink speciality does not exists
    SpecialityCatalogue --> SpecialistController: NULL
    SpecialistController --> RestAPI: exception
    RestAPI --> ReactApp : http_response

else #LightBlue speciality exists
    SpecialityCatalogue -> Speciality ** : <<create>>
    SpecialityCatalogue --> SpecialistController : speciality
    SpecialistController -> SpecialityCertificateController: addSpecialityCertificate(specialityId, docs)
    SpecialityCertificateController -> SpecialityCertificate ** :<<create>>
    SpecialityCertificateController -> SpecialityCertificateCatalogue : save(certificate)
    SpecialityCertificateCatalogue -> Database: sql_query
    return
    SpecialityCertificateCatalogue --> SpecialityCertificateController
    SpecialityCertificateController --> SpecialistController: speciality_certificate
    SpecialistController -> Specialist : addCertificate(specialityCertificate)
    return
    SpecialistController -> SpecialistCatalogue: save(specialist)
    SpecialistCatalogue ->Database: sql_query
    return
    SpecialistCatalogue --> SpecialistController
    SpecialistController -> SpecialityCertificateDTO **: <<create>>
    SpecialistController --> RestAPI: certificateDTO
    RestAPI --> ReactApp : http_response
end 

ReactApp --> user: message
@enduml