@startuml addSpeciality
hide footbox
title "افزودن نوع خدمت"
actor       "مدیر" as root
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":SpecialityController" as SpecialityController
participant ":SpecialityCatalogue" as SpecialityCatalogue
participant ":Speciality" as Speciality
participant ":SpecialityDTO" as SpecialityDTO
database Database
note left of root
    مدیر وارد سامانه
     شده باشد
end note
note left of root
    مدیر دسترسی ویرایش
    انواع خدمت را داشته باشد
end note
    
root -> ReactApp : SubmitAddSpecialityForm()
ReactApp -> RestAPI : http_request
RestAPI -> SpecialityController : addSepciality(parentId, name)
SpecialityController -> SpecialityCatalogue : findByName(name)
SpecialityCatalogue -> Database : sql_query
return tuple
alt #Pink speciality found
    SpecialityCatalogue -> Speciality **: <<create>>
    SpecialityCatalogue --> SpecialityController: speciality
    SpecialityController --> RestAPI: exception
    RestAPI --> ReactApp: http_response
else #LightBlue speciality not found
    SpecialityCatalogue --> SpecialityController: NULL
    SpecialityController -> Speciality **: <<create>>
    SpecialityController -> SpecialityCatalogue : save(speciality)
    SpecialityCatalogue -> Database: sql_query
    return
    SpecialityCatalogue --> SpecialityController
    SpecialityController -> SpecialityDTO **: <<create>>
    SpecialityController --> RestAPI: specialityDTO
    RestAPI --> ReactApp : http_response 
end

ReactApp --> root: message
@enduml