@startuml logout

hide footbox
title "نمایش مشکل فنی"
actor "مدیر" as root
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":TechnicalIssueController" as TechnicalIssueController
participant ":TechnicalIssueCatalogue" as TechnicalIssueCatalogue
participant ":TechnicalIssue" as TechnicalIssue

database Database

note left of root
    مدیر باید در سامانه
    وارد شده باشد
end note
ref over root, ReactApp, RestAPI, TechnicalIssueController, TechnicalIssueCatalogue, Database : نمایش مشکلات فنی

root -> ReactApp: answerTechnicalIssue()
ReactApp -> RestAPI : http_request
RestAPI -> TechnicalIssueController: answerTechnicalIssue()
TechnicalIssueController -> TechnicalIssueCatalogue : findById()
TechnicalIssueCatalogue -> Database : sql_query
return tuple
TechnicalIssueCatalogue -> TechnicalIssue ** :<<create>>
TechnicalIssueCatalogue --> TechnicalIssueController : technicalIssue
TechnicalIssueCatalogue -> TechnicalIssue: answer()
return
TechnicalIssueController -> TechnicalIssueCatalogue : save()
TechnicalIssueCatalogue -> Database :sql_query
return 
TechnicalIssueCatalogue --> TechnicalIssueController
TechnicalIssueController --> RestAPI
RestAPI --> ReactApp : http_response
ReactApp --> root: message

@enduml