@startuml logout
hide footbox
title "پاسخ به مشکل فنی"
actor "مدیر" as root
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":TechnicalIssueController" as TechnicalIssueController
participant ":TechnicalIssueCatalogue" as TechnicalIssueCatalogue
participant ":TechnicalIssue" as TechnicalIssue
participant ":TechnicalIssueDTO" as TechnicalIssueDTO
database Database

note left of root
    مدیر باید در سامانه
    وارد شده باشد
end note
note left of root
     مدیر باید دسترسی رسیدگی
  به مشکلات فنی را داشته باشد. 
end note

root -> ReactApp: answerTechnicalIssue()
ReactApp -> RestAPI : http_request
RestAPI -> TechnicalIssueController: answerTechnicalIssue()
TechnicalIssueController -> TechnicalIssueCatalogue : findById()
TechnicalIssueCatalogue -> Database : sql_query
return tuple
alt#Gold #Pink technicalIssue not found

    TechnicalIssueCatalogue --> TechnicalIssueController: NULL
    TechnicalIssueController --> RestAPI: exception
    RestAPI --> ReactApp : http_response

else #LightBlue

    TechnicalIssueCatalogue -> TechnicalIssue ** :<<create>>
    TechnicalIssueCatalogue --> TechnicalIssueController : technicalIssue
    TechnicalIssueController -> TechnicalIssue: answer()
    return
    TechnicalIssueController -> TechnicalIssueCatalogue : save()
    TechnicalIssueCatalogue -> Database :sql_query
    return 
    TechnicalIssueCatalogue --> TechnicalIssueController
    TechnicalIssueController -> TechnicalIssueDTO **: <<create>>
    TechnicalIssueController --> RestAPI: technicalIssueDTO
    RestAPI --> ReactApp : http_response

end
ReactApp --> root: message

@enduml