@startuml logout
hide footbox
title "پاک‌کردن نوع خدمت متخصص"
actor       "متخصص" as user
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":SpecialistController" as SpecialistController
participant ":SpecialistCatalogue" as SpecialistCatalogue
participant ":Specialist" as Specialist
participant ":SpecialityCertificateController" as SpecialityCertificateController
participant ":SpecialityCertificateCatalogue" as SpecialityCertificateCatalogue
database Database

note left of user
    متخصص باید در سامانه
    وارد شده باشد
end note

user -> ReactApp: SubmitRemoveCertificateForm()
ReactApp -> RestAPI : http_request
RestAPI -> SpecialistController : removeCertificate()
SpecialistController -> SpecialistCatalogue : findById()
SpecialistCatalogue -> Database: sql_query
return: tuple
SpecialistCatalogue -> Specialist ** :<<create>>
SpecialistCatalogue --> SpecialistController : specialist
SpecialistController -> Specialist: getAllCertificates():
return certificates
alt#gold #pink specialityCertificate doesn't exist in certificates

    SpecialistController --> RestAPI
    RestAPI --> ReactApp : http_response

else #lightblue specialist has specialityCertificate

    SpecialistController -> SpecialityCertificateController: removeSpecialityCertificate()
    SpecialityCertificateController -> SpecialityCertificateCatalogue : delete()
    SpecialityCertificateCatalogue -> Database: sql_query
    return
    SpecialityCertificateCatalogue --> SpecialityCertificateController
    SpecialityCertificateController --> SpecialistController
    SpecialistController --> RestAPI
    RestAPI --> ReactApp : http_response

end
ReactApp --> user: message

@enduml