@startuml logout
hide footbox
title "پاک کردن نوع خدمت متخصص"
actor       "متخصص" as user
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":SpecialistController" as SpecialistController
participant ":SpecialistCatalogue" as SpecialistCatalogue
participant ":Specialist" as Specialist
participant ":SpecialityCertificateController" as SpecialityCertificateController
participant ":SpecialityCertificate" as SpecialityCertificate
participant ":SpecialityCertificateCatalogue" as SpecialityCertificateCatalogue
database Database

note left of user
    متخصص باید در سامانه
    وارد شده باشد
end note

user -> ReactApp: 
ReactApp -> RestAPI : http_request
RestAPI -> SpecialistController : removeCertificate()
SpecialistController -> SpecialistCatalogue : findById()
SpecialistCatalogue -> Database: sql_query
return: tuple
SpecialistCatalogue -> Specialist ** :<<create>>
SpecialistCatalogue --> SpecialistController : specialist
SpecialistController -> SpecialityCertificateController: removeSpecialityCertificate()
SpecialityCertificateController -> SpecialityCertificate !!
SpecialityCertificateController -> SpecialityCertificateCatalogue : delete()
SpecialityCertificateCatalogue -> Database: sql_query
return
SpecialityCertificateCatalogue --> SpecialityCertificateController
SpecialityCertificateController --> SpecialistController

SpecialistController -> Specialist : Certificate()
return
SpecialistController -> SpecialistCatalogue: save()
SpecialistCatalogue ->Database: sql_query
return
SpecialistCatalogue --> SpecialistController
SpecialistController --> RestAPI
RestAPI --> ReactApp : http_response
RestAPI --> user: message

@enduml