@startuml addSpeciality
hide footbox
title "پاک‌کردن نوع خدمت"
actor       "مدیر" as root
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":SpecialityController" as SpecialityController
participant ":SpecialityCatalogue" as SpecialityCatalogue
participant ":Speciality" as Speciality
database Database
note left of root
    مدیر وارد سامانه
     شده باشد
end note
note left of root
    مدیر دسترسی ویرایش
    انواع خدمت را داشته باشد
end note
    
root -> ReactApp : SubmitAddSpecialityForm()
ReactApp -> RestAPI : http_request
RestAPI -> SpecialityController : removeSepciality(specialistId)

SpecialityController -> SpecialityCatalogue : findByName(name)
SpecialityCatalogue -> Database : sql_query
return tuple

alt#Gold #Pink speciality not found

    SpecialityCatalogue --> SpecialityController: NULL
    SpecialityController --> RestAPI: exception
    RestAPI --> ReactApp : http_response

else #LightBlue speciality found

    SpecialityCatalogue -> Speciality **: <<create>>
    SpecialityCatalogue --> SpecialityController: speciality
    SpecialityController -> SpecialityCatalogue : delete(speciality)
    SpecialityCatalogue -> Database : sql_query
    return
    SpecialityCatalogue --> SpecialityController
    SpecialityController --> RestAPI
    RestAPI --> ReactApp: http_response

end

ReactApp --> root: message
@enduml