@startuml logout

hide footbox
title "دیدن دیدگاه ها "
actor "مدیر" as root
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":FeedbackController" as FeedbackController
participant ":FeedbackCatalogue" as FeedbackCatalogue
participant ":Feedback" as Feedback
participant ":FeedbackDTO" as FeedbackDTO
database Database

note left of root
    مدیر باید در سامانه
    وارد شده باشد
end note
note left of root
    مدیر باید دسترسی دیدن 
    دیدگاه ها را داشته باشد
end note

root -> ReactApp: showFeedbacks()
ReactApp -> RestAPI : http_request
RestAPI -> FeedbackController: showAllFeedbacks()
FeedbackController -> FeedbackCatalogue : findAll
FeedbackCatalogue -> Database : sql_query
return tuples
loop
    FeedbackCatalogue -> Feedback **: <<create>>
end
FeedbackCatalogue --> FeedbackController : feedbacks
loop
    FeedbackController -> FeedbackDTO **: <<create>>
end
FeedbackController --> RestAPI: feedbacks
note right of FeedbackController
    feedbacks are list of feedbackDTO
end note
RestAPI --> ReactApp : http_response
ReactApp --> root: message

@enduml