@startuml spcialistAcceptOrRejectService
hide footbox
title "پذیرش یا رد درخواست خدمت"
actor       "متخصص" as specialist
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":ServiceController" as ServiceController
participant ":ServiceCatalogue" as ServiceCatalogue
participant ":Service" as Service
participant ":Chat" as Chat
participant ":ServiceDTO" as ServiceDTO
participant ":SpecialistCatalogue" as SpecialistCatalogue
participant ":SpecialistCandidateFinderStrategy" as SpecialistCandidateFinderStrategy
participant ":Announcement" as Announcement
database Database
note left of specialist
    متخصص باید در سامانه
    وارد شده باشد
end note

specialist -> ReactApp: SubmitAcceptServiceRequest()
ReactApp -> RestAPI: http_request
RestAPI -> ServiceController: acceptService()

alt#Gold #Pink specialist is performing number of active services more than threshold

    ServiceController --> RestAPI: exception
    RestAPI --> ReactApp: http_response

else #LightBlue

    ServiceController -> ServiceCatalogue: findById()
    ServiceCatalogue -> Database: sql_query
    return tuple
    alt#Gold #Pink service not found

        ServiceCatalogue --> ServiceController: NULL
        ServiceController --> RestAPI: exception
        RestAPI --> ReactApp: http_response

    else #LightBlue

        ServiceCatalogue -> Service **: <<create>>
        ServiceCatalogue --> ServiceController: service

        alt#Gold #Pink specialist isn't candidate of service || service status is not WAITING_FOR_SPECIALIST_ACCEPTANCE

            ServiceController --> RestAPI: exception
            RestAPI --> ReactApp: http_response

        else #LightBlue

            alt specialist rejects service

                ref over ServiceController, SpecialistCandidateFinderStrategy, SpecialistCatalogue, Database: جستجو متخصص کاندید
                ServiceController -> Service: setCandidateSpecialist()
                return
                ServiceController -> Announcement: <<send>> Notification
                Announcement -> Announcement: notifyUser()
                Announcement -->: notification
                note right of Announcement
                    ایمیل جزئیات درخواست خدمت
                    به مشتری کاندید جدید ارسال می‌شود
                end note

            else specialist accepts service

                ServiceController -> Service: updateToNextState()
                Service -> Chat **: <<create>>
                return
                Service --> ServiceController
                ServiceController -> Announcement: <<send>> Notification
                Announcement -> Announcement: notifyUser()
                Announcement -->: notification
                note right of Announcement
                    ایمیل تایید درخواست خدمت توسط
                    متخصص به مشتری ارسال می‌شود
                end note

            end
            ServiceController -> ServiceCatalogue: save()
            ServiceCatalogue -> Database: sql_query
            return service
            ServiceController -> ServiceDTO **: <<create>>
            ServiceController --> RestAPI: serviceDTO
            RestAPI --> ReactApp: http_response

        end

    end

end
ReactApp --> specialist: message
@enduml