@startuml logout
' TODO: check speciality does exist
hide footbox
title "ایجاد مشکل فنی"
actor "کاربر" as user
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":TechnicalIssueController" as TechnicalIssueController
participant ":TechnicalIssueCatalogue" as TechnicalIssueCatalogue
participant ":TechnicalIssue" as TechnicalIssue
participant ":TechnicaIssuelDTO" as TechnicaIssuelDTO
database Database

note left of user
    کاربر باید در سامانه
    وارد شده باشد
end note

user -> ReactApp: submitTechnicalIssueForm()
ReactApp -> RestAPI : http_request
RestAPI -> TechnicalIssueController: submitTechnicalIssue(content, writer)
TechnicalIssueController -> TechnicalIssue ** :<<create>>
TechnicalIssueController -> TechnicalIssueCatalogue : save(technicalIssue)
TechnicalIssueCatalogue -> Database : sql_query
return tuple
TechnicalIssueCatalogue -> TechnicalIssue **: <<create>>
TechnicalIssueCatalogue --> TechnicalIssueController: technicalIssue
TechnicalIssueController --> TechnicaIssuelDTO **: <<create>>
TechnicalIssueController --> RestAPI: technicaIssuelDTO
RestAPI --> ReactApp : http_response
ReactApp --> user: message

@enduml