@startuml updateProfile
hide footbox
title "ویرایش مشخصات حساب کاربری"
actor       کاربر as user
participant ReactApp
participant ":RestAPI" as RestAPI
participant ":UserController" as UserController
participant ":UserCatalogue" as UserCatalogue
participant ":User" as User
participant ":UserProfileDTO" as UserProfileDTO
database Database
note left of user
    کاربر باید در سامانه
    وارد شده باشد
end note

user -> ReactApp: SubmitProfileForm()
ReactApp -> RestAPI: http_request
RestAPI -> UserController : updateProfile(new_profile, context)
UserController -> UserCatalogue: findById(id)
UserCatalogue -> Database: sql_query
return tuple
UserCatalogue -> User **: <<create>>
UserCatalogue --> UserController: user

UserController -> UserProfileDTO **: <<create>>
UserController -> User: isValidProfile(profile)
return

alt#Gold #Pink invalid profile

    UserController --> RestAPI: exception
    RestAPI --> ReactApp: http_response

else #LightBlue valid profile

    UserController -> User: updateProfile(new_profile, context)
    return
    UserController -> UserCatalogue: save(user)
    UserCatalogue -> Database: sql_query
    return
    UserController -> UserProfileDTO **: <<create>>
    UserController --> RestAPI: userDTO
    RestAPI --> ReactApp: http_response
end

ReactApp --> user: message
@enduml