@startuml AnswerTicket
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title پاسخ به مشکل فنی 
|مدیر فناوری اطلاعات|
start
#AAAAAA:نمایش مشکلات فنی <$rake>;
:انتخاب مشکل فنی برای پاسخ‌دهی;
note left: مدیر فناوری اطلاعات باید در سامانه وارد شده باشد.
|زیر سامانه فنی|
:ارسال فرم پاسخ‌دهی به مدیر فناوری اطلاعات;
|مدیر فناوری اطلاعات|
:وارد کردن پاسخ مشکل فنی;
|زیر سامانه فنی|
:ثبت پاسخ به مشکل فنی;
|زیر سامانه آگهی|
:ارسال پیام پاسخ مشکل فنی به کاربر ایجاد کننده;
stop
@enduml