@startuml ApproveSpecialistService
Title تایید نوع خدمت متخصص
!theme _none_ 
|مدیر|
start
:درخواست نمایش فهرست انواع خدمت;
note left: مدیر باید در سامانه وارد شده باشد.
note left: مدیر انواع خدمت تایید نشده را از سامانه درخواست می‌کند.
|زیر سامانه کاربری|
:جمع‌آوری و ارسال فهرست انواع خدمت متخصصان;
|مدیر|
:درخواست مشاهده نوع خدمت مدنظر;
note left: مدیر می‌بایست دسترسی مشاهده انواع\nخدمت متخصص را داشته باشد.
|زیر سامانه کاربری|
:نمایش مدارک مربوط به نوع خدمت متخصص به مدیر;
|مدیر|
if (بررسی مدارک) then (<color:green>[تایید مدارک])
|زیر سامانه کاربری|
:به‌روزرسانی وضعیت نوع خدمت متخصص;
note right: مدیر می‌بایست دسترسی تایید یا عدم تایید\nانواع خدمت متخصص را داشته باشد.
|زیر سامانه آگهی|
  :ارسال آگهی تایید نوع خدمت به متخصص;
else (<color:red>[عدم تایید مدارک])
  :ارسال آگهی عدم تایید نوع خدمت به متخصص;
|زیر سامانه کاربری|
endif
stop
@enduml
