@startuml CreateTicket
Title ایجاد مشکل فنی 
|کاربر|
start
:‌درخواست ثبت مشکل فنی;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه فنی|
:ارسال فرم ثبت مشکل فنی به کاربر;
|کاربر|
:وارد نمودن مشکل فنی;
|زیر سامانه فنی|
:ثبت مشکل فنی;
|زیر سامانه آگهی|
:ارسال پیغام ثبت مشکل فنی به مدیران;
stop
@enduml