@startuml UserCriticismSuggestion
Title ثبت دیدگاه 
|کاربر|
start
:درخواست ثبت دیدگاه;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه ارزیابی|
:ارسال فرم ثبت دیدگاه به کاربر;
note right: این فرم شامل جعبه متنی بوده و به عنوان فرم انتقادات و\nپیشنهادات کاربران در مورد سامانه می‌باشد..
|کاربر|
:پر کردن فرم ثبت دیدگاه;
|زیر سامانه ارزیابی|
:ثبت دیدگاه کاربر;
|زیر سامانه آگهی|
:ارسال آگهی ثبت موفقیت آمیز دیدگاه به مشتری;
:ارسال آگهی ثبت دیدگاه به مدیران;
|زیر سامانه ارزیابی|
stop
@enduml