@startuml CustomerCancelServices
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title لغو درخواست‌ خدمت مشتری
|مشتری|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rake>;
note left: مشتری باید در سامانه وارد شده باشد.
:درخواست لغو درخواست خدمت مدنظر;
|زیر سامانه خدمت‌رسانی|
if (وضعیت درخواست خدمت) then ([درحال انجام])
:تغییر وضعیت درخواست خدمت به لغو شده;
|زیر سامانه آگهی|
:ارسال آگهی لغو شدن درخواست خدمت به متخصص;
:ارسال آگهی لغو شدن موفقیت آمیز درخواست خدمت به مشتری;
else ([اتمام و نظرسنجی])
|زیر سامانه آگهی|
:ارسال آگهی عدم امکان لغو شدن درخواست خدمت به مشتری;
endif
stop
@enduml