@startuml CustomerAcceptSpecialist
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title پذیرش متخصص
!theme _none_ 
|مشتری|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rate>;
:انتخاب درخواست خدمت مدنظر برای مشاهده جزئیات;
note left: مشتری باید در سامانه وارد شده باشد.
note left: مشتری درخواست خدمت را ثبت کرده باشد و درخواست خدمت\nبه مرحله انتخاب و تایید متخصص رسیده باشد.
note left: متخصص انجام درخواست خدمت را پذیرفته باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش جزئیات درخواست خدمت به همراه نمایه متخصص کاندید;
|مشتری|
if () then ([پذیرش متخصص])
|زیر سامانه خدمت‌رسانی|
:تغییر وضعیت درخواست خدمت به در حال انجام ;
|زیر سامانه آگهی|
:ارسال آگهی تایید برای انجام درخواست خدمت به متخصص;
else ([رد متخصص])
|زیر سامانه آگهی|
:ارسال آگهی عدم تایید انجام\nدرخواست خدمت به متخصص;
|زیر سامانه خدمت‌رسانی|
:انتخاب متخصص بعدی در فهرست متخصصان\nواجد شرایط انجام درخواست به عنوان کاندیدای بعدی;
|زیر سامانه آگهی|
:ارسال پیام در انتظار تایید انجام درخواست خدمت به آن متخصص;
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml