@startuml Login
Title ورود به حساب کاربری
!theme _none_ 
|کاربر|
start
:وارد کردن اطلاعات خواست شده در فرم ورود;
|زیر سامانه کاربری|
:دریافت اطلاعات لازم شامل نام کاربری یا پست الکترونیکی و کلمه عبور از کاربر;
if (بررسی اطلاعات دریافت شده) then (<color:green>[تایید اطلاعات])
:ایجاد مجوز ورود;
:دریافت اطلاعات حساب کاربری;
:User]
:هدایت کاربر به پنل کاربری;
|زیر سامانه آگهی|
  :ارسال آگهی موفقیت آمیز بودن ورود به کاربر;
else (<color:red>[عدم تایید اطلاعات])
|زیر سامانه آگهی|
  :ارسال آگهی عدم تایید اطلاعات به کاربر;
|زیر سامانه کاربری|
endif
stop
@enduml
