@startuml Logout
Title خروج از حساب کاربری
!theme _none_ 
|کاربر|
start
:درخواست خروج از سامانه;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه کاربری|
:ابطال مجوز ورود;
:خروج کاربر از سامانه;
stop
@enduml
