@startuml ManagerRemoveSpeciaity
Title پاک‌کردن نوع خدمت
|مدیر|
start
:درخواست نمایش فهرست نوع خدمت;
note left: مدیر باید در سامانه وارد شده باشد.
note left : مدیر باید دسترسی ویرایش\nفهرست نوع خدمت را داشته باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش فهرست نوع خدمت به مدیر;
|مدیر|
:انتخاب نوع خدمت;
:درخواست حذف نوع خدمت;
if (انواع خدمت فرزند نوع خدمت انتخاب شده) then (<color:green>[عدم وجود فرزند])
|زیر سامانه خدمت‌رسانی|
:پاک کردن نوع خدمت;
:حذف نوع خدمت از فهرست انواع خدمت;
|زیر سامانه آگهی|
:ارسال آگهی به‌روزرسانی فهرست نوع خدمت به مدیر;
else (<color:red>[وجود حداقل یک فرزند])
|زیر سامانه آگهی|
:ارسال آگهی عدم موفقیت آمیز بودن\nویرایش فهرست نوع خدمت به مدیر;
note right: به علت وجود حداقل یک نوع خدمت فرزند،\nامکان حذف نوع خدمت وجود ندارد.
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml