@startuml ManagerRemoveQuestionReviews
Title کم‌کردن پرسش‌ ارزیابی‌
|مدیر|
start
:درخواست نمایش فهرست پرسش‌های ارزیابی;
note left: مدیر باید در سامانه وارد شده باشد.
note left : مدیر باید دسترسی ویرایش\nپرسش‌های ارزیابی را داشته باشد.
|زیر سامانه ارزیابی‌|
:ارسال فهرست پرسش‌های ارزشیابی;
note right: فهرست پرسش‌های ارزیابی‌ برای مشتری و\nمتخصص نمایش داده می‌شوند.
|مدیر|
:انتخاب یک پرسش ارزیابی برای حذف;
|زیر سامانه ارزیابی‌|
:پاک کردن پرسش ارزیابی;
:حذف پرسش‌ارزیابی از فهرست پرسش‌ها;
stop
@enduml