@startuml ManagerCancelServices
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title لغو درخواست‌ خدمت مدیر
|مدیر|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rake>;
note left: مدیر باید در سامانه وارد شده باشد.
:درخواست لغو درخواست خدمت مدنظر;
note left: مدیر باید دسترسی ویرایش\nدرخواست‌های خدمت را داشته باشد.
|زیر سامانه خدمت‌رسانی|
:تغییر وضعیت درخواست خدمت به لغو شده;
if (وضعیت درخواست خدمت) then ([در انتظار تایید متخصص] or [در حال انجام])
|زیر سامانه آگهی|
:ارسال آگهی لغو شدن درخواست خدمت به متخصص;
endif
|زیر سامانه آگهی|
:ارسال آگهی لغو شدن درخواست خدمت به مشتری;
:ارسال آگهی لغو شدن موفقیت آمیز درخواست خدمت به مدیر;
stop
@enduml