@startuml ManagerAddSpeciaity
Title افزودن نوع خدمت
|مدیر|
start
:درخواست افزودن نوع خدمت;
note left: مدیر باید در سامانه وارد شده باشد.
note left : مدیر باید دسترسی ویرایش\nفهرست نوع خدمت را داشته باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش فرم افزودن نوع خدمت به مدیر;
|مدیر|
:پر کردن فرم افزودن نوع خدمت;
note left: این فرم شامل نام نوع خدمت و نام دسته نوع خدمت (نوع خدمت پدر) می‌باشد
note left: مدیر می‌تواند دسته نوع خدمت را خالی بگذارد.
if (بررسی فرم دریافت شده از مدیر) then (<color:green>[تایید اطلاعات])
|زیر سامانه خدمت‌رسانی|
:نوع خدمت]
:ثبت نوع خدمت در فهرست انواع خدمت;
|زیر سامانه آگهی|
:ارسال آگهی به‌روزرسانی فهرست نوع خدمت به مدیر;
else (<color:red>[عدم تایید فهرست جدید])
|زیر سامانه آگهی|
:ارسال آگهی عدم موفقیت آمیز بودن\nویرایش فهرست نوع خدمت به مدیر;
note right: مدیر نوع خدمت تکراری را در سامانه ثبت کند.
note right: دسته نوع خدمت مشخص شده در سامانه مجود ندارد.
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml