@startuml ManagerAddQuestionReviews
Title افزودن پرسش‌ ارزیابی‌
|مدیر|
start
:درخواست افزودن یک پرسش‌ ارزیابی‌;
note left: مدیر باید در سامانه وارد شده باشد.
note left : مدیر باید دسترسی ویرایش\nپرسش‌های ارزیابی را داشته باشد.
|زیر سامانه ارزیابی‌|
:فرم افزودن پرسش ارزشیابی;
note right: فرم ایجاد پرسش ارزیابی‌ برای مشتری و\nمتخصص نمایش داده می‌شوند.
|مدیر|
:پر کردن فرم پرسش‌ ارزیابی;
|زیر سامانه ارزیابی‌|
:پرسش‌ ارزشیابی]
:ثبت پرسش‌ ارزشیابی جدید به فهرست پرسش‌ها;
stop
@enduml