@startuml ManagerUpdateNumberOfAcceptingServices
Title تغییر تعداد پذیرش درخواست‌های خدمت در حال انجام‌
|مدیر|
start
:درخواست ویرایش تنظیمات درخواست‌های خدمت;
note left: مدیر باید در سامانه وارد شده باشد.
note left : مدیر باید دسترسی ویرایش\nتنظیمات درخواست خدمت را داشته باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش تنظیمات فعلی تعداد درخواست‌های\nخدمت قابل پذیرش توسط متخصصان;
note right: این تنظیمات بر اساس بازه\nامتیاز متخصصان می باشد.
|مدیر|
:تغییر تنظیمات تعداد پذیرش درخواست‌های\nخدمت همزمان بر اساس امتیاز;
|زیر سامانه خدمت‌رسانی|
if (بررسی تنظیمات جدید) then (<color:green>[تایید تنظیمات جدید])
:به‌روزرسانی تنظیمات مربوط به\nپذیرش درخواست‌های خدمت;
|زیر سامانه آگهی|
:ارسال آگهی به‌روزرسانی تنظیمات مدیر;
else (<color:red>[عدم تایید تنظیمات جدید])
|زیر سامانه آگهی|
:ارسال آگهی عدم موفقیت آمیز بودن\nویرایش تنظیمات به مدیر;
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml