@startuml ManagerSignup
Title ساخت حساب کاربری مدیر
!theme _none_ 
|مدیر فناوری اطلاعات|
start
:وارد کردن اطلاعات خواست شده در فرم ثبت‌نام;
note left: مدیر فناوری اطلاعات باید\n در سامانه وارد شده باشد.
|زیر سامانه کاربری|
:دریافت اطلاعات لازم شامل نام کاربری، پست الکترونیکی و \nکلمه عبور از مدیر فناوری اطلاعات;
if (بررسی اطلاعات دریافت شده) then (<color:green>[تایید اطلاعات])
  :ساخت حساب کاربری جدید;
  :مدیر]
  note right: مدیر با سطح دسترسی اولیه برابر با \nسطح دسترسی مشتری ایجاد می شود.
  :ذخیره و افزودن به فهرست حساب‌های مدیر;
|زیر سامانه آگهی|
  :ارسال آگهی موفقیت آمیز بودن ساخت حساب مدیر \nبه مدیر فناوری اطلاعات;
else (<color:red>[عدم تایید اطلاعات])
|زیر سامانه آگهی|
  :ارسال آگهی عدم موفقیت آمیز بودن ساخت حساب مدیر \nبه مدیر فناوری اطلاعات;
|زیر سامانه کاربری|
endif
stop
@enduml
