@startuml RegisterService
Title ثبت درخواست خدمت
|کاربر|
start
:درخواست ثبت درخواست خدمت;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش فرم اولیه ثبت درخواست خدمت به کاربر;
|کاربر|
if () then ([کاربر = مدیر])
repeat :;
:مدیر مشتری درخواست دهنده را مشخص می کند;
note left: مدیر باید سطح دسترسی لازم را\nبرای ثبت درخواست‌ خدمت داشته باشد.
|زیر سامانه کاربری|
:جستجو برای پیدا کردن مشتری;
|زیر سامانه آگهی|
backward :ارسال آگهی عدم یافت مشتری به مدیر;
|زیر سامانه کاربری|
repeat while () is (<color:red>[عدم وجود مشتری])
endif
|زیر سامانه خدمت‌رسانی|
:ارسال فرم درخواست خدمت به کاربر;
|کاربر|
:پر کردن فرم ثبت درخواست خدمت;
|زیر سامانه خدمت‌رسانی|
if (بررسی اطلاعات دریافت شده در ارتباط با درخواست خدمت) then (<color:green>[تایید اطلاعات])
:ساخت یک درخواست خدمت;
:درخواست خدمت]
|کاربر|
if (انتخاب متخصصی خاص برای انجام درخواست خدمت) then ([بله])
repeat :;
:وارد نمودن نام کاربری یا ایمیل متخصص\nمد نظر برای انجام درخواست;
|زیر سامانه کاربری|
:جستجو برای پیدا کردن متخصص;
|زیر سامانه آگهی|
backward :ارسال آگهی عدم یافت متخصص به کاربر;
repeat while () is (<color:red>[عدم وجود متخصص])
:ارسال آگهی به آن متخصص برای مشاهده\nو تایید انجام درخواست خدمت;
else ([خیر])
|زیر سامانه خدمت‌رسانی|
:استخراج متخصصان واجد شرایط برای انجام درخواست;
|زیر سامانه آگهی|
:ارسال آگهی به اولین متخصص در فهرست برای\nمشاهده و تایید انجام درخواست خدمت;
endif
|زیر سامانه خدمت‌رسانی|
:تعیین متخصص به عنوان کاندیدای انجام درخواست خدمت;
else (<color:red>[عدم تایید اطلاعات])
|زیر سامانه آگهی|
  :ارسال آگهی عدم تایید اطلاعات درخواست ثبت شده به کاربر;
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml