@startuml UserReviewServices
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title ارزیابی درخواست‌ خدمت 
|کاربر|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rake>;
:مشاهده درخواست خدمت مدنظر;
note left: کاربر باید در سامانه وارد شده باشد.
note left: درخواست خدمت به وضعیت اتمام و نظرسنجی رسیده باشد.
note left: کاربر می‌تواند از نوع مشتری یا متخصص باشد.
|زیر سامانه ارزیابی|
:ارسال فرم ارزیابی درخواست خدمت به کاربر;
note right: این فرم شامل جعبه متنی و معیار‌های\nارزیابی از پیش تعیین شده می‌باشد.
|کاربر|
if ()
:پر کردن فرم نظر سنجی;
|زیر سامانه ارزیابی|
:ثبت داده‌های حاصل از فرم ارزیابی\nدرخواست خدمت دریافت شده از کاربر;
if () then ([کاربر = مشتری])
:به‌روزرسانی امتیاز متخصص انجام دهنده درخواست خدمت;
endif
|کاربر|
else ([انصراف از نظر‌سنجی])
endif
|زیر سامانه ارزیابی|
stop
@enduml