@startuml ShowServices
Title جستجو درخواست‌های خدمت
|کاربر|
start
:درخواست جستجو در درخواست‌های خدمت;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه خدمت‌رسانی|
if () then ([کاربر = مشتری])
:نمایش فیلتر‌های جستجو به مشتری;
note left: این فیلتر‌ها حاوی وضعیت کنونی و تاریخ ثبت می‌باشند 
else ([کاربر = مدیر])
|زیر سامانه خدمت‌رسانی|
:نمایش فیلتر‌های جستجو به مدیر;
note right: مدیر باید سطح دسترسی لازم را برای مشاهده\nدرخواست‌های خدمت داشته باشد.
note right: این فیلتر‌ها حاوی وضعیت کنونی، تاریخ ثبت، امتیاز مشتری\nو خالی بودن یا نبودن نظر مشتری و ... می‌باشند 
endif
|کاربر|
:تعیین مقادیر فیلتر‌های جستجو;
|زیر سامانه خدمت‌رسانی|
:استخراج فهرست درخواست‌های خدمت مربوط\nبه کاربر بر اساس فیلتر‌های مطلوب او;
:نمایش فهرست درخواست‌های خدمت به کاربر;
stop
@enduml