@startuml SearchSpecialists
Title جستجو متخصصان
|کاربر|
start
:درخواست جستجو در فهرست متخصصان;
|زیر سامانه کاربری|
:نمایش فیلتر‌های جستجو به کاربر;
|کاربر|
:تعیین مقادیر فیلتر‌های جستجو;
note right: این فیلتر‌ها حاوی نام، نوع خدمت،\nامتیاز و.. می‌باشند 
|زیر سامانه کاربری|
:استخراج فهرست متخصصان سامانه\nبر اساس فیلتر‌های مطلوب کاربر;
:نمایش فهرست متخصصان به کاربر;
stop
@enduml