@startuml SearchSpecialities
Title جستجو نوع خدمت
|کاربر|
start
:درخواست جستجو در فهرست انواع خدمت;
|زیر سامانه خدمت‌رسانی|
:نمایش فیلتر‌های جستجو به کاربر;
|کاربر|
:تعیین مقادیر فیلتر‌های جستجو;
note right: این فیلتر‌ها حاوی کلید‌واژه و.. می‌باشند 
|زیر سامانه خدمت‌رسانی|
:استخراج فهرست انواع خدمت سامانه\nبر اساس فیلتر‌های مطلوب کاربر;
:نمایش فهرست انواع خدمت به کاربر;
note right: فهرست انواع خدمت به صورت درختی و مرتب شده\nبا حروف الفبا به کاربر نمایش داده می‌شود.
stop
@enduml