@startuml UserSendMessage.start
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title ارسال پیام
|کاربر|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rake>;
note left: کاربر باید در سامانه وارد شده باشد.
note left: کاربر می‌تواند از نوع مشتری یا متخصص باشد.
:انتخاب درخواست خدمت;
note left: درخواست خدمت به وضعیت در انتظار پذیرش مشتری\nیا در حال انجام رسیده باشد.
|زیر سامانه پیام‌رسانی|
:نمایش صفحه پیام کاربر با طرف دیگر;
note right: اگر کاربر مشتری باشد، طرف دیگر\nمتخصص و بالعکس خواهد بود.
|کاربر|
:وارد نمودن پیام;
|زیر سامانه پیام‌رسانی|
:ثبت پیام کاربر در صفحه پیام دو کاربر;
|زیر سامانه آگهی|
:ارسال آگهی دریافت پیام جدید به کاربر طرف دیگر پیام;
|زیر سامانه پیام‌رسانی|
stop
@enduml