@startuml ShowTickets
Title نمایش مشکلات فنی 
|مدیر|
start
:‌درخواست مشاهده مشکلات فنی;
note left: مدیر باید در سامانه وارد شده باشد.
note left:  مدیر باید سطح دسترسی مشاهده\nمشکلات فنی را داشته باشد.
|زیر سامانه فنی|
:ارسال فهرست مشکلات فنی ثبت شده کاربران به مدیر;
note right: این فهرست بر اساس تاریخ ثبت و وضعیت آن\n (رسیدگی/عدم رسیدگی) مرتب شده است.
stop
@enduml