@startuml ShowSpecialists
Title نمایش فهرست متخصصان
|کاربر|
start
:درخواست نمایش فهرست متخصصان;
:تعیین وضعیت متخصص;
note right: وضعیت متخصص مانند تایید شده،\nتایید نشده، غیر فعال و ... می‌باشد.
|زیر سامانه کاربری|
:استخراج فهرست متخصصان سامانه بر اساس وضعیت مطلوب کاربر;
:نمایش فهرست متخصصان به کاربر;
stop
@enduml