@startuml ShowManagers
Title نمایش فهرست مدیران
|مدیر|
start
:درخواست نمایش فهرست مدیران;
note left: مدیر باید در سامانه وارد شده باشد.
note left: مدیر باید سطح دسترسی لازم را \nبرای مشاهده سایر مدیران داشته باشد.
|زیر سامانه کاربری|
:استخراج فهرست مدیران سامانه;
:نمایش فهرست مدیران;
stop
@enduml