@startuml ShowCriticismsSuggestions
Title ‌دیدن دیدگاه‌ها 
|مدیر|
start
:‌درخواست مشاهده دیدگاه‌ها;
note left: مدیر باید در سامانه وارد شده باشد.
note left: مدیر باید سطح دسترسی مشاهده\nدیدگاه‌ها را داشته باشد.
|زیر سامانه ارزیابی|
:ارسال فهرست دید‌گاه‌های ثبت شده کاربران به مدیر;
note right: این فهرست بر اساس تاریخ\nثبت مرتب شده است.
stop
@enduml