@startuml Signup
Title ساخت حساب کاربری
!theme _none_ 
|کاربر|
start
:وارد کردن اطلاعات خواست شده در فرم ثبت‌نام;
:مشخص کردن نوع حساب کاربری;
note left: مشتری یا متخصص
|زیر سامانه کاربری|
:دریافت اطلاعات لازم شامل نام کاربری، پست الکترونیکی و کلمه عبور از کاربر;
if (بررسی اطلاعات دریافت شده) then (<color:green>[تایید اطلاعات])
  :ساخت حساب کاربری جدید;
  if () then ([کاربر = مشتری])
  :مشتری]
  :ذخیره و افزودن به فهرست حساب‌های مشتری;
  else ([کاربر = متخصص])
  :متخصص]
  note right: حساب متخصص حاوی نمایه با وضعیت\n"عدم تایید" ایجاد خواهد شد
  :ذخیره و افزودن به فهرست حساب‌های متخصص;
  endif
|زیر سامانه آگهی|
  :ارسال آگهی موفقیت آمیز بودن ساخت حساب به کاربر;
else (<color:red>[عدم تایید اطلاعات])
|زیر سامانه آگهی|
  :ارسال آگهی عدم تایید اطلاعات به کاربر;
|زیر سامانه کاربری|
endif
stop
@enduml
