@startuml SpecialistAddService
Title  افزودن نوع خدمت متخصص
!theme _none_ 
|متخصص|
start
:متخصص درخواست مشاهده نمایه خود را می‌کند;
note left: متخصص قبلا در سامانه وارد شده است.
|زیر سامانه کاربری|
:ارسال نمایه به متخصص;
|متخصص|
:درخواست افزودن نوع خدمت;
|زیر سامانه کاربری|
:ارسال فرم افزودن نوع خدمت;
note right: این فرم شامل بخش‌هایی برای بارگذاری مدارک \n تخصصی مانند گواهی‌های تحصیلی، فنی و حرفه‌ای می‌باشد.
|متخصص|
:پر کردن فرم افزودن نوع خدمت;
|زیر سامانه کاربری|
:ایجاد نوع خدمت بر اساس فرم;
note right:نوع خدمت افزوده شده از نوع تایید نشده می‌باشد.
:افزودن نوع خدمت به فهرست نوع خدمت‌های متخصص;
|زیر سامانه آگهی|
:ارسال آگهی بررسی نوع خدمت افزوده شده به مدیران;
|زیر سامانه کاربری|
stop
@enduml