@startuml SpecialistRemoveService
Title  پاک‌کردن نوع خدمت متخصص
!theme _none_ 
|متخصص|
start
:متخصص درخواست مشاهده نمایه خود را می‌کند;
note left: متخصص قبلا در سامانه وارد شده است.
|زیر سامانه کاربری|
:ارسال نمایه به متخصص;
|متخصص|
:درخواست نمایش فهرست نوع‌های خدمت;
|زیر سامانه کاربری|
:ارسال فهرست نوع‌های خدمت;
|متخصص|
:انتخاب نوع خدمت برای حذف;
:درخواست حذف نوع خدمت انتخاب شده;
|زیر سامانه کاربری|
:حذف نوع خدمت متخصص;
:به‌روزرسانی فهرست نوع‌های خدمت متخصص;
|زیر سامانه آگهی|
:ارسال آگهی موفقیت‌آمیز بودن حذف نوع خدمت به متخصص;
|زیر سامانه کاربری|
stop
@enduml