@startuml SpecialistAcceptService
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title پذیرش یا رد درخواست خدمت
!theme _none_ 
|متخصص|
start
#AAAAAA:جستجو درخواست‌های خدمت <$rake>;
note left: متخصص درخواست‌های خدمتی که برای تایید انجام\nبه او محول شده است را جستجو می کند.
:انتخاب درخواست خدمتی برای بررسی و مشاهده;
note left: متخصص باید در سامانه وارد شده باشد.
note left: متخصص باید در وضعیت تایید شده باشد.
note left: درخواست خدمت ایجاد شده توسط مشتری باید\nدر وضعیت 'در انتظار پذیرش متخصص' باشد.
|زیر سامانه خدمت‌رسانی|
:نمایش جزئیات درخواست خدمت به متخصص;
|متخصص|
if () then ([پذیرش درخواست خدمت])
|زیر سامانه خدمت‌رسانی|
:تغییر وضعیت درخواست خدمت به\nدر انتظار پذیرش مشتری;
|زیر سامانه پیام‌رسانی|
:ایجاد صفحه پیام بین متخصص و مشتری;
|زیر سامانه آگهی|
:ارسال آگهی پذیرش انجام درخواست خدمت به مشتری;
else ([رد درخواست خدمت])
|زیر سامانه آگهی|
:ارسال آگهی عدم پذیرش درخواست به مشتری;
|زیر سامانه خدمت‌رسانی|
:انتخاب متخصص بعدی در فهرست متخصصان واجد شرایط\nانجام درخواست به عنوان کاندیدای بعدی;
|زیر سامانه آگهی|
:ارسال پیام در انتظار تایید انجام درخواست خدمت به آن متخصص;
endif
|زیر سامانه خدمت‌رسانی|
stop
@enduml