@startuml UpdateAcessLevel
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
Title تغییر دسترسی مدیر
!theme _none_ 
|مدیر فناوری اطلاعات|
start
#AAAAAA:نمایش فهرست مدیران <$rake>;
:درخواست ویرایش سطح دسترسی یک مدیر;
note left: مدیر فناوری اطلاعات باید در \nسامانه وارد شده باشد.
|زیر سامانه کاربری|
:نمایش سطوح دسترسی مدیر مدنظر;
|مدیر فناوری اطلاعات|
:تغییر سطوح دسترسی مدیر;
|زیر سامانه کاربری|
:به‌روزرسانی سطوح دسترسی مدیر;
|زیر سامانه آگهی|
  :ارسال آگهی به روز رسانی سطوح دسترسی به مدیر;
  :ارسال آگهی موفقیت آمیر بودن عملیات تغییر سطوح \nدسترسی به مدیر فناوری اطلاعات;
|زیر سامانه کاربری|
stop
@enduml
