@startuml UpdateProfile
Title ویرایش مشخصات حساب کاربری
!theme _none_ 
|کاربر|
start
:وارد کردن اطلاعات خواست شده \nدر فرم ویرایش مشخصات;
note left: کاربر باید در سامانه وارد شده باشد.
|زیر سامانه کاربری|
:دریافت اطلاعات تغییر یافته از کاربر;
if (بررسی تغییرات جدید) then (<color:green>[تایید اطلاعات])
:به‌روزرسانی اطلاعات حساب کاربری;
|زیر سامانه آگهی|
  :ارسال آگهی موفقیت آمیز بودن عملیات\n ویرایش مشخصات به کاربر;
else (<color:red>[عدم تایید اطلاعات])
|زیر سامانه آگهی|
  :ارسال آگهی عدم تایید ویرایش اطلاعات به کاربر;
|زیر سامانه کاربری|
endif
stop
@enduml
